import type { Metadata } from "next";
import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/navbar";
import { MobileBottomBar } from "./components/mobile-bottombar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${workSans.variable} antialiased`}
      >
        <div className="h-[calc(100dvh-56px)] lg:h-full overflow-auto">
          {children}
        </div>
        <MobileBottomBar />
      </body>
    </html>
  );
}
