import type { Metadata } from "next";
import { Geist, Geist_Mono, Work_Sans } from "next/font/google";
import "./globals.css";
import { satoshi, itcClearface } from "./font";
import { MobileBottomBar } from "./components/mobile-bottombar";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${satoshi.variable}
          ${itcClearface.variable}
          ${workSans.variable}
        `}
      >
        <div className="min-h-dvh pb-[18px]">
          {children}
        </div>
        <MobileBottomBar />
      </body>
    </html>
  );
}
